name: ecfoo
mail: tim@electriccitizen.com
slogan: ''
page:
  403: ''
  404: /search404
  front: /node
admin_compact_mode: false
weight_select_max: 100
langcode: en
default_langcode: en
_core:
  default_config_hash: oFGejEEA5thoklyMT_5vOvqJFtP4YzOvl3HxRH4jmC8
uuid: 88012fcb-9d2b-4dc5-b993-c0e8a88d3124
